baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "LuxDoc | The association of the young researchers in Luxembourg"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo-luxdoc.png"
  logo_footer = "images/logo-luxdoc-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  payconiq_img = "images/payconiq.jpeg"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "LuxDoc | The association of the young researchers in Luxembourg"
    tagline               = "WE RESEARCH, WE CONNECT, WE THRIVE"
    primary_button        = "See Our Past Events"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.team]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "OUR EVENTS"
    subtitle  = "Organizing events and seeking to make the academic community in Luxembourg stronger and more connected."
    view_project = "view event"
    more_works = "MORE EVENTS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Contact us"
    primary_button_url  = "contact"
    secondary_button    = "Become a Member!"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "98, Av. du Bois<br>c/o Erik Pillon<br>Luxembourg, L-1250"
      email   = "luxdoc2022@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About LuxDoc"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Past Events"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Become a Member"
          url  = "membership"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "YouTube"
          url  = "https://www.youtube.com/@luxdoc472"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/_luxdoc_/"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/LuxDoc.asbl"
      # Footer Service
      [params.footer.service]
        title       = "LuxDoc asbl"
        description = "no profit association of the young researchers and doctoral students in Luxembourg"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
